import os
import re
import json
import arxiv
import yaml
import logging
import argparse
import datetime
import requests
import subprocess

logging.basicConfig(
    format="[%(asctime)s %(levelname)s] %(message)s",
    datefmt="%m/%d/%Y %H:%M:%S",
    level=logging.INFO,
)

base_url = "https://arxiv.paperswithcode.com/api/v0/papers/"
github_url = "https://api.github.com/search/repositories"
arxiv_url = "http://arxiv.org/"


def load_config(config_file: str) -> dict:
    """
    config_file: input config file path
    return: a dict of configuration
    """

    # make filters pretty
    def pretty_filters(**config) -> dict:
        keywords = dict()
        EXCAPE = '"'
        QUOTA = ""  # NO-USE
        OR = "OR"  # TODO

        def parse_filters(filters: list):
            ret = ""
            for idx in range(0, len(filters)):
                filter = filters[idx]
                if len(filter.split()) > 1:
                    ret += EXCAPE + filter + EXCAPE
                else:
                    ret += QUOTA + filter + QUOTA
                if idx != len(filters) - 1:
                    ret += OR
            return ret

        for k, v in config["keywords"].items():
            keywords[k] = parse_filters(v["filters"])
        return keywords

    with open(config_file, "r") as f:
        config = yaml.load(f, Loader=yaml.FullLoader)
        config["kv"] = pretty_filters(**config)
        logging.info(f"config = {config}")
    return config


def get_authors(authors, first_author=False, last_author=False):
    output = str()
    if first_author:
        output = authors[0]
    elif last_author:
        output = authors[-1]
    else:
        output = ", ".join(str(author) for author in authors)
    return output


def sort_papers(papers):
    output = dict()
    keys = list(papers.keys())
    keys.sort(reverse=True)
    for key in keys:
        output[key] = papers[key]
    return output


import requests


def get_code_link(qword: str) -> str:
    """
    This short function was auto-generated by ChatGPT.
    I only renamed some params and added some comments.
    @param qword: query string, eg. arxiv ids and paper titles
    @return paper_code in github: string, if not found, return None
    """
    # query = f"arxiv:{arxiv_id}"
    query = f"{qword}"
    params = {"q": query, "sort": "stars", "order": "desc"}
    r = requests.get(github_url, params=params)
    results = r.json()
    code_link = None
    if results["total_count"] > 0:
        code_link = results["items"][0]["html_url"]
    return code_link


def get_daily_papers(topic, query="slam", max_results=2):
    content = dict()
    content_to_web = dict()
    search_engine = arxiv.Search(
        query=query, max_results=max_results, sort_by=arxiv.SortCriterion.SubmittedDate
    )

    for result in search_engine.results():
        paper_id = result.get_short_id()
        paper_title = result.title
        paper_url = result.entry_id
        paper_abstract = result.summary.replace("\n", " ")
        paper_last_author = get_authors(result.authors, last_author=True)
        update_time = result.published.date()  # 또는 updated.date()
        comments = result.comment

        ver_pos = paper_id.find("v")
        paper_key = paper_id[0:ver_pos] if ver_pos != -1 else paper_id
        paper_url = arxiv_url + "abs/" + paper_key
        repo_url = None
        project_url = None
        if comments:
            urls = re.findall(r"(https?://[^\s,;]+)", comments)
            for url in urls:
                if "github.com" in url or "gitlab.com" in url:
                    repo_url = url
                else:
                    project_url = url  # GitHub가 아닌 링크는 프로젝트 페이지로 간주

        abstract_html = f"<details>Abstract: {paper_abstract}</details>"

        links = f"[ArXiv]({paper_url})"
        if repo_url != None:
            links += f" / [Code]({repo_url})"
        if project_url != None:
            links += f" / [Web]({project_url})"

        content[paper_key] = (
            f"|**{update_time}**|**{paper_title}**<br>{abstract_html}|{paper_last_author} Team|{links}|\n"
        )
        content_to_web[paper_key] = (
            f"- {update_time}, **{paper_title}**, {paper_last_author} Team [ArXiv]({paper_url})"
        )

    return {topic: content}, {topic: content_to_web}


def update_paper_links(filename):
    """
    weekly update paper links in json file
    """

    def parse_arxiv_string(s):
        parts = s.split("|")
        date = parts[1].strip()
        title = parts[2].strip()
        authors = parts[3].strip()
        arxiv_id = parts[4].strip()
        code = parts[5].strip()
        arxiv_id = re.sub(r"v\d+", "", arxiv_id)
        return date, title, authors, arxiv_id, code

    with open(filename, "r") as f:
        content = f.read()
        if not content:
            m = {}
        else:
            m = json.loads(content)

        json_data = m.copy()

        for keywords, v in json_data.items():
            logging.info(f"keywords = {keywords}")
            for paper_id, contents in v.items():
                contents = str(contents)

                update_time, paper_title, paper_first_author, paper_url, code_url = (
                    parse_arxiv_string(contents)
                )

                contents = "|{}|{}|{}|{}|{}|\n".format(
                    update_time, paper_title, paper_first_author, paper_url, code_url
                )
                json_data[keywords][paper_id] = str(contents)
                logging.info(f"paper_id = {paper_id}, contents = {contents}")

                valid_link = False if "|null|" in contents else True
                if valid_link:
                    continue
        with open(filename, "w") as f:
            json.dump(json_data, f)


def update_json_file(filename, data_dict):
    # 1. 기존 데이터 로드
    if os.path.exists(filename):
        with open(filename, "r") as f:
            content = f.read()
            json_data = json.loads(content) if content else {}
    else:
        json_data = {}

    # 2. 새 데이터 업데이트
    for data in data_dict:
        for keyword in data.keys():
            if keyword in json_data:
                json_data[keyword].update(data[keyword])
            else:
                json_data[keyword] = data[keyword]

    # 3. 아카이브 분리 (30일 기준)
    recent_data, archived_data = prune_old_papers(json_data, days_limit=30)

    # 4. 최근 데이터 저장 (메인 README용)
    with open(filename, "w") as f:
        json.dump(recent_data, f)

    # 5. 아카이브 데이터 누적 저장
    archive_filename = filename.replace(".json", "_archive.json")
    if archived_data:
        old_archive = {}
        if os.path.exists(archive_filename):
            with open(archive_filename, "r") as f:
                content = f.read()
                old_archive = json.loads(content) if content else {}

        # 아카이브 데이터 병합
        for kw, papers in archived_data.items():
            if kw in old_archive:
                old_archive[kw].update(papers)
            else:
                old_archive[kw] = papers

        with open(archive_filename, "w") as f:
            json.dump(old_archive, f)


def json_to_md(
    filename,
    md_filename,
    keyword_list,  # keyword_list 인자 추가
    task="",
    to_web=False,
    use_title=True,
    use_tc=True,
    show_badge=True,
    use_b2t=False,
):
    """
    @param filename: str (JSON 파일 경로)
    @param md_filename: str (생성할 마크다운 파일 경로)
    @param keyword_list: list (정렬 순서를 위한 키워드 리스트)
    @return None
    """

    def pretty_math(s: str) -> str:
        ret = ""
        match = re.search(r"\$.*\$", s)
        if match == None:
            return s
        math_start, math_end = match.span()
        space_trail = space_leading = ""
        if s[:math_start][-1] != " " and "*" != s[:math_start][-1]:
            space_trail = " "
        if s[math_end:][0] != " " and "*" != s[math_end:][0]:
            space_leading = " "
        ret += s[:math_start]
        ret += f"{space_trail}${match.group()[1:-1].strip()}${space_leading}"
        ret += s[math_end:]
        return ret

    DateNow = datetime.date.today()
    DateNow = str(DateNow).replace("-", ".")

    with open(filename, "r") as f:
        content = f.read()
        data = json.loads(content) if content else {}

    # 파일 초기화
    with open(md_filename, "w") as f:
        pass

    # 마크다운 작성
    with open(md_filename, "a", encoding="utf-8") as f:
        # 웹 페이지용 헤더
        if (use_title == True) and (to_web == True):
            f.write("---\nlayout: default\n---\n\n")

        # 상단 배지 (config.yaml의 정보 반영 권장)
        if show_badge == True:
            # 리포지토리 이름을 robotics-arxiv-daily로 수정
            f.write(f"[![Contributors][contributors-shield]][contributors-url]\n")
            f.write(f"[![Forks][forks-shield]][forks-url]\n")
            f.write(f"[![Stargazers][stars-shield]][stars-url]\n")
            f.write(f"[![Issues][issues-shield]][issues-url]\n\n")

        if use_title == True:
            f.write(f"## Updated on {DateNow}\n")
        else:
            f.write(f"> Updated on {DateNow}\n")

        f.write("> Usage instructions: [here](./docs/README.md#usage)\n\n")

        # 1. Table of Contents (keyword_list 순서 적용)
        if use_tc == True:
            f.write("<details>\n  <summary>Table of Contents</summary>\n  <ol>\n")
            for keyword in keyword_list:
                if keyword not in data or not data[keyword]:
                    continue
                kw_anchor = keyword.replace(" ", "-").lower()
                f.write(f"    <li><a href=#{kw_anchor}>{keyword}</a></li>\n")
            f.write("  </ol>\n</details>\n\n")

        # 2. 본문 내용 (keyword_list 순서 적용)
        for keyword in keyword_list:
            if keyword not in data or not data[keyword]:
                continue

            day_content = data[keyword]
            f.write(f"## {keyword}\n\n")
            if to_web == False: 
                f.write(f"<details>\n")
                f.write(
                    f"  <summary><b>{keyword} Papers (Click to expand)</b></summary>\n\n"
                )
            if use_title == True:
                if to_web == False:
                    f.write(
                        "|Publish Date|Title & Abstract|Authors|Links|\n|---|---|---|---|\n"
                    )
                else:
                    f.write("| Publish Date | Title & Abstract | Authors | Links |\n")
                    f.write(
                        "|:---------|:-----------------------|:---------|:------|\n"
                    )
            # 날짜별 정렬
            day_content = sort_papers(day_content)

            for _, v in day_content.items():
                if v is not None:
                    # 수식 가독성 처리 및 내용 작성
                    f.write(pretty_math(v))

            if to_web == False:
                f.write(f"\n</details>\n\n")
            else:
                f.write(f"\n")
                top_info = f"#Updated on {DateNow}"
                top_info = top_info.replace(' ','-').replace('.','')
                f.write(f"<p align=right>(<a href={top_info.lower()}>back to top</a>)</p>\n\n")
            

        # 하단 링크 정보 (사용자 계정 및 리포지토리 이름 반영)
        if show_badge == True:
            user = "cold-young"
            repo = "robotics-paper-daily"
            f.write(
                f"[contributors-shield]: https://img.shields.io/github/contributors/{user}/{repo}.svg?style=for-the-badge\n"
            )
            f.write(
                f"[contributors-url]: https://github.com/{user}/{repo}/graphs/contributors\n"
            )
            f.write(
                f"[forks-shield]: https://img.shields.io/github/forks/{user}/{repo}.svg?style=for-the-badge\n"
            )
            f.write(f"[forks-url]: https://github.com/{user}/{repo}/network/members\n")
            f.write(
                f"[stars-shield]: https://img.shields.io/github/stars/{user}/{repo}.svg?style=for-the-badge\n"
            )
            f.write(f"[stars-url]: https://github.com/{user}/{repo}/stargazers\n")
            f.write(
                f"[issues-shield]: https://img.shields.io/github/issues/{user}/{repo}.svg?style=for-the-badge\n"
            )
            f.write(f"[issues-url]: https://github.com/{user}/{repo}/issues\n\n")

    logging.info(f"{task} finished")


def prune_old_papers(json_data, days_limit=60):
    import datetime

    recent_data = {}
    archived_data = {}
    threshold_date = datetime.date.today() - datetime.timedelta(days=days_limit)
    for keyword, papers in json_data.items():
        recent_data[keyword] = {}
        archived_data[keyword] = {}
        for p_id, p_content in papers.items():
            try:
                date_str = p_content.split("|")[1].replace("**", "").strip()
                p_date = datetime.datetime.strptime(date_str, "%Y-%m-%d").date()

                if p_date >= threshold_date:
                    recent_data[keyword][p_id] = p_content
                else:
                    archived_data[keyword][p_id] = p_content
            except:
                recent_data[keyword][p_id] = p_content  # 파싱 실패 시 유지

    return recent_data, archived_data


def demo(**config):
    # TODO: use config
    data_collector = []
    data_collector_web = []

    keywords = config["kv"]
    keyword_list = list(keywords.keys())
    max_results = config["max_results"]
    publish_readme = config["publish_readme"]
    publish_gitpage = config["publish_gitpage"]
    show_badge = config["show_badge"]

    b_update = config["update_paper_links"]
    logging.info(f"Update Paper Link = {b_update}")
    if config["update_paper_links"] == False:
        logging.info(f"GET daily papers begin")
        for topic, keyword in keywords.items():
            logging.info(f"Keyword: {topic}")
            data, data_web = get_daily_papers(
                topic, query=keyword, max_results=max_results
            )
            data_collector.append(data)
            data_collector_web.append(data_web)
            print("\n")
        logging.info(f"GET daily papers end")

    # 1. update README.md file
    if publish_readme:
        json_file = config["json_readme_path"]
        md_file = config["md_readme_path"]
        # update paper links
        if config["update_paper_links"]:
            update_paper_links(json_file)
        else:
            # update json data
            update_json_file(json_file, data_collector)
        # json data to markdown
        json_to_md(
            json_file,
            md_file,
            keyword_list,  # keyword_list 전달
            task="Update Readme",
            show_badge=show_badge,
        )

    # 2. update docs/index.md file (to gitpage)
    if publish_gitpage:
        json_file = config["json_gitpage_path"]
        md_file = config["md_gitpage_path"]
        if config["update_paper_links"]:
            update_paper_links(json_file)
        else:
            update_json_file(json_file, data_collector)
        json_to_md(
            json_file,
            md_file,
            keyword_list,  # keyword_list 전달
            task="Update GitPage",
            to_web=True,
            show_badge=show_badge,
            use_tc=False,
            use_b2t=False,
        )


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config_path", type=str, default="config.yaml", help="configuration file path"
    )
    parser.add_argument(
        "--update_paper_links",
        default=False,
        action="store_true",
        help="whether to update paper links etc.",
    )
    args = parser.parse_args()
    config = load_config(args.config_path)
    config = {**config, "update_paper_links": args.update_paper_links}
    demo(**config)

    try:
        subprocess.run(["git", "add", "."], check=True)
        subprocess.run(["git", "commit", "-m", "commit"], check=True)
        subprocess.run(["git", "push", "-u", "origin", "main"], check=True)
        print("Git commands executed successfully.")
    except subprocess.CalledProcessError as e:
        pass
